name: speedtest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0-69.2.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  liquid_progress_indicator: ^0.4.0
  syncfusion_flutter_gauges: ^20.1.52
  internet_speed_test: ^1.5.0
  ipapico_flutter: ^0.0.4
  connectivity_plus: ^2.3.0
  font_awesome_flutter: ^10.1.0
  easy_splash_screen: ^1.0.3
  screenshot: ^1.2.3
  path_provider: ^2.0.9
  esys_flutter_share_plus: ^2.1.0
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2
  shimmer: ^2.0.0
  intl:
  flutter_slidable: ^1.2.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
    image_path: "assets/icon/logo.png" 
    android: true
    ios: true

flutter: 
  uses-material-design: true
  assets:
      - assets/images/flags/
      - assets/images/

